In [1]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
train = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')
y = train['Survived'].values
from sklearn.datasets import load_iris

In [2]:
# 트레이닝, 테스트 데이터 >>성별<< 이진화, female = 1, female = 0
embarked_mapping = {'female': 1, 'male': 0}
train['Sex'] = train['Sex'].map(embarked_mapping)
test['Sex'] = test['Sex'].map(embarked_mapping)

# embarked null값 그냥 S로 채운 후 S, C, Q값 숫자로 바꿔주기
train = train.fillna({"Embarked": "S"})
test = test.fillna({"Embarked": "S"})
embarked_mapping = {'S': 1, 'C': 2, 'Q': 3}
train['Embarked'] = train['Embarked'].map(embarked_mapping)
test['Embarked'] = test['Embarked'].map(embarked_mapping)

# fare 매핑
test['Fare'] = test['Fare'].fillna(test['Fare'].median())
train['Fare'] = np.where(train['Fare'] <= 7.91, 0, train['Fare'])
train['Fare'] = np.where((train['Fare'] > 7.91) & (train['Fare'] <= 14.454), 1, train['Fare'])
train['Fare'] = np.where((train['Fare'] > 14.454) & (train['Fare'] <= 31), 2, train['Fare'])
train['Fare'] = np.where(train['Fare'] > 31, 3, train['Fare'])
train['Fare'] = train['Fare'].astype(int)
test['Fare'] = np.where(test['Fare'] <= 7.91, 0, test['Fare'])
test['Fare'] = np.where((test['Fare'] > 7.91) & (test['Fare'] <= 14.454), 1, test['Fare'])
test['Fare'] = np.where((test['Fare'] > 14.454) & (test['Fare'] <= 31), 2, test['Fare'])
test['Fare'] = np.where(test['Fare'] > 31, 3, test['Fare'])
test['Fare'] = test['Fare'].astype(int)

#age 매핑
age_avg = train['Age'].mean()
train['Age'] = train['Age'].fillna(age_avg)
test['Age'] = test['Age'].fillna(age_avg)
test['Age'] = train['Age'].astype(int)
test['Age'] = test['Age'].astype(int)
train['Age'] = np.where(train['Age'] <= 16, 0, train['Age'])
train['Age'] = np.where((train['Age'] > 16) & (train['Age'] <= 32), 1, train['Age'])
train['Age'] = np.where((train['Age'] > 32) & (train['Age'] <= 48), 2, train['Age'])
train['Age'] = np.where((train['Age'] > 48) & (train['Age'] <= 64), 3, train['Age'])
train['Age'] = np.where(train['Age'] > 64, 4, train['Age'])
test['Age'] = np.where(test['Age'] <= 16, 0, test['Age'])
test['Age'] = np.where((test['Age'] > 16) & (test['Age'] <= 32), 1, test['Age'])
test['Age'] = np.where((test['Age'] > 32) & (test['Age'] <= 48), 2, test['Age'])
test['Age'] = np.where((test['Age'] > 48) & (test['Age'] <= 64), 3, test['Age'])
test['Age'] = np.where(test['Age'] > 64, 4, test['Age'])
train['Age'] = train['Age'].astype(int)
test['Age'] = test['Age'].astype(int)

# 없앨 feature들,,
train = train.drop(['PassengerId'], axis=1)
test = test.drop(['PassengerId'], axis=1)
train = train.drop(['Cabin'], axis=1)
test = test.drop(['Cabin'], axis=1)
train = train.drop(['Name'], axis=1)
test = test.drop(['Name'], axis=1)
train = train.drop(['Ticket'], axis=1)
test = test.drop(['Ticket'], axis=1)
train = train.drop(['Survived'], axis=1)

In [3]:
test

     Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
0         3    0    1      0      0     0         3
1         3    1    2      1      0     0         1
2         2    0    1      0      0     1         3
3         3    0    2      0      0     1         1
4         3    1    2      1      1     1         1
5         3    0    1      0      0     1         1
6         3    1    3      0      0     0         3
7         2    0    0      1      1     2         1
8         3    1    1      0      0     0         2
9         3    0    0      2      0     2         1
10        3    0    0      0      0     0         1
11        1    0    3      0      0     2         1
12        1    1    1      1      0     3         1
13        2    0    2      1      0     2         1
14        1    1    0      1      0     3         1
15        2    1    3      1      0     2         2
16        2    0    0      0      0     1         3
17        3    0    1      0      0     0         2
18        3    1    1      1      0     1         1
19        3    1    1      0      0     0         2
20        1    0    2      1      0     3         2
21        3    0    2      0      1     0         1
22        1    1    0      0      0     3         1
23        1    0    1      0      1     3         2
24        1    1    0      1      3     3         2
25        3    0    2      1      0     2         1
26        1    1    1      0      1     3         2
27        3    0    1      0      0     0         2
28        1    0    1      0      0     2         1
29        3    0    1      2      0     2         2
..      ...  ...  ...    ...    ...   ...       ...
388       3    0    1      0      0     0         3
389       3    0    1      3      1     2         1
390       1    0    2      0      0     3         1
391       1    1    1      0      1     3         1
392       3    0    1      0      2     2         1
393       2    0    1      0      0     1         1
394       3    0    1      3      1     2         1
395       1    1    1      1      0     3         1
396       3    0    1      0      0     0         3
397       1    1    2      1      1     3         2
398       3    0    1      0      0     0         1
399       3    0    1      0      0     0         3
400       1    1    2      0      0     3         1
401       2    0    1      1      0     2         1
402       1    1    1      0      1     3         2
403       1    0    1      0      0     3         1
404       1    0    1      1      0     2         2
405       2    0    2      0      0     1         2
406       2    0    3      1      0     1         1
407       1    0    0      1      1     3         2
408       3    1    1      0      0     0         3
409       3    1    1      1      1     1         1
410       3    1    1      0      0     0         3
411       1    1    1      1      0     3         3
412       3    1    2      0      0     0         1
413       3    0    1      0      0     1         1
414       1    1    2      0      0     3         2
415       3    0    1      0      0     0         1
416       3    0    2      0      0     1         1
417       3    0    1      1      1     2         2

[418 rows x 7 columns]

In [4]:
X = []
for row in train.iterrows():
    index, data = row
    X.append(data.tolist())
X_test = []
for row in test.iterrows():
    index, data = row
    X_test.append(data.tolist())

In [5]:
X = np.array(X)
X_test = np.array(X_test)

In [6]:
X

array([[3, 0, 1, ..., 0, 0, 1],
       [1, 1, 2, ..., 0, 3, 2],
       [3, 1, 1, ..., 0, 1, 1],
       ...,
       [3, 1, 1, ..., 2, 2, 1],
       [1, 0, 1, ..., 0, 2, 2],
       [3, 0, 1, ..., 0, 0, 3]])

In [7]:
class LogisticRegression:
    # lr = learning rate
    # num_iter: 반복횟수
    # fit_intercept: 모형에 상수항이 있는가 없는가
    # verbose: 모두프린트할건지??
    def __init__(self, lr=0.0001, num_iter=100000, fit_intercept=True, verbose=False):
        self.lr = lr
        self.num_iter = num_iter
        self.fit_intercept = fit_intercept
        self.verbose = verbose
    
    def __add_intercept(self, X):
        # X의 row 개수만큼의 row 가진 배열 리스트 생성 (1 * X.shape[0])
        intercept = np.ones((X.shape[0], 1))
        return np.concatenate((intercept, X), axis=1)
    
    def __sigmoid(self, z):
        return 1 / (1 + np.exp(-z))
    
    def __loss(self, h, y):
        return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()
    
    def fit(self, X, y):
        # 만약 상수항이 있으면 X에 상수항 추가
        if self.fit_intercept:
            X = self.__add_intercept(X)
        
        # weights initialization
        self.theta = np.zeros(X.shape[1])
        
        for i in range(self.num_iter):
            z = np.dot(X, self.theta)
            h = self.__sigmoid(z)
            # gradient 미분값?
            gradient = np.dot(X.T, (h - y)) / y.size
            self.theta -= self.lr * gradient
            
            # verbose == True 일 때에만 출력한다
            if(self.verbose == True and i % 1000 == 0):
                z = np.dot(X, self.theta)
                h = self.__sigmoid(z)
                print(f'loss: {self.__loss(h, y)} \t')
    
    def predict_prob(self, X):
        if self.fit_intercept:
            X = self.__add_intercept(X)
    
        return self.__sigmoid(np.dot(X, self.theta))
    
    def predict(self, X, threshold=0.5):
        return self.predict_prob(X) >= threshold

In [8]:
model = LogisticRegression(lr=0.001, num_iter=100000)

In [9]:
%time model.fit(X, y)

loss: 0.6929117619608571
loss: 0.6171175102943969
loss: 0.587472752824105
loss: 0.5675528734910865
loss: 0.5527352164153182
loss: 0.5409380022002278
loss: 0.5311318664834265
loss: 0.5227580136036242
loss: 0.5154830115357408
loss: 0.5090895193060313
loss: 0.5034247648329272
loss: 0.49837481786361815
loss: 0.4938509384652979
loss: 0.48978184392523433
loss: 0.4861090194044557
loss: 0.4827836791851717
loss: 0.47976467686671664
loss: 0.47701699574816053
loss: 0.4745106159414944
loss: 0.4722196397124996
loss: 0.4701216019761453
loss: 0.46819691831469396
loss: 0.46642843788649874
loss: 0.4648010779248003
loss: 0.46330152263880636
loss: 0.46191797352239766
loss: 0.4606399410636792
loss: 0.4594580700424935
loss: 0.45836399225105884
loss: 0.45735020173225477
loss: 0.4564099486049308
loss: 0.4555371483077647
loss: 0.4547263036937933
loss: 0.45397243788414243
loss: 0.4532710361695125
loss: 0.4526179955526691
loss: 0.4520095807706107
loss: 0.4514423858336519
loss: 0.4509133002799767
loss: 0.45041947947581823
loss: 0.4499583183992031
loss: 0.44952742843381693
loss: 0.4491246167726936
loss: 0.44874786809202477
loss: 0.4483953282057796
loss: 0.44806528945387947
loss: 0.4477561776118929
loss: 0.4474665401398306
loss: 0.4471950356125849
loss: 0.44694042419570024
loss: 0.4467015590481014
loss: 0.4464773785486937
loss: 0.4462668992568171
loss: 0.4460692095277303
loss: 0.445883463713931
loss: 0.44570887689141947
loss: 0.4455447200571942
loss: 0.4453903157504884
loss: 0.4452450340556744
loss: 0.4451082889494734
loss: 0.4449795349592366
loss: 0.44485826410266965
loss: 0.4447440030825445
loss: 0.4446363107127302
loss: 0.4445347755543345
loss: 0.4444390137429229
loss: 0.4443486669897019
loss: 0.44426340074126386
loss: 0.4441829024840044
loss: 0.44410688018067723
loss: 0.44403506082775246
loss: 0.44396718912332145
loss: 0.44390302623625355
loss: 0.4438423486681728
loss: 0.44378494720059636
loss: 0.44373062592027024
loss: 0.4436792013163657
loss: 0.4436305014437633
loss: 0.44358436514715704
loss: 0.4435406413411746
loss: 0.4434991883421211
loss: 0.44345987324733316
loss: 0.443422571358467
loss: 0.4433871656453567
loss: 0.4433535462473571
loss: 0.4433216100093426
loss: 0.443291260049762
loss: 0.4432624053583667
loss: 0.44323496042141414
loss: 0.4432088448723327
loss: 0.44318398316598645
loss: 0.44316030427483216
loss: 0.44313774140538864
loss: 0.44311623173356546
loss: 0.4430957161575083
loss: 0.4430761390667222
loss: 0.44305744812632664
loss: 0.44303959407538573
loss: 0.4430225305383335
loss: 0.44300621384858907
Wall time: 3.15 s

In [151]:
preds = model.predict(X)

In [152]:
(preds == y).mean()

0.7912457912457912

In [153]:
model.theta

array([ 0.13054928, -0.7668626 ,  2.56465472, -0.50611044, -0.42763173,
       -0.15098334,  0.39371784,  0.30259081])

In [156]:
preds_test = model.predict(X_test)

In [157]:
test_index = 892
submission = pd.DataFrame({"PassengerId": [], "Survived": [] })
for item in preds_test:
    if (item == False):
        submission.loc[test_index] = [test_index, 0]
    else:
        submission.loc[test_index] = [test_index, 1]
    test_index += 1
submission['PassengerId'] = submission['PassengerId'].astype(int)
submission['Survived'] = submission['Survived'].astype(int)
submission.to_csv("submission.csv", index=False)