In [18]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
train = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')

In [19]:
# 정답 저장!
y = train['Survived']

## 데이터 전처리

In [20]:
# 트레이닝, 테스트 데이터 >>성별<< 이진화, female = 1, female = 0
embarked_mapping = {'female': 1, 'male': 0}
train['Sex'] = train['Sex'].map(embarked_mapping)
test['Sex'] = test['Sex'].map(embarked_mapping)

# embarked null값 그냥 S로 채운 후 S, C, Q값 숫자로 바꿔주기
train = train.fillna({"Embarked": "S"})
test = test.fillna({"Embarked": "S"})
embarked_mapping = {'S': 1, 'C': 2, 'Q': 3}
train['Embarked'] = train['Embarked'].map(embarked_mapping)
test['Embarked'] = test['Embarked'].map(embarked_mapping)

# 이름 길이(Name_length) 추가하기
train['Name_length'] = train['Name'].apply(len)
test['Name_length'] = test['Name'].apply(len)

# fare 매핑
test['Fare'] = test['Fare'].fillna(test['Fare'].median())
train['Fare'] = np.where(train['Fare'] <= 7.91, 0, train['Fare'])
train['Fare'] = np.where((train['Fare'] > 7.91) & (train['Fare'] <= 14.454), 1, train['Fare'])
train['Fare'] = np.where((train['Fare'] > 14.454) & (train['Fare'] <= 31), 2, train['Fare'])
train['Fare'] = np.where(train['Fare'] > 31, 3, train['Fare'])
train['Fare'] = train['Fare'].astype(int)
test['Fare'] = np.where(test['Fare'] <= 7.91, 0, test['Fare'])
test['Fare'] = np.where((test['Fare'] > 7.91) & (test['Fare'] <= 14.454), 1, test['Fare'])
test['Fare'] = np.where((test['Fare'] > 14.454) & (test['Fare'] <= 31), 2, test['Fare'])
test['Fare'] = np.where(test['Fare'] > 31, 3, test['Fare'])
test['Fare'] = test['Fare'].astype(int)

#age 매핑
age_avg = train['Age'].mean()
train['Age'] = train['Age'].fillna(age_avg)
test['Age'] = test['Age'].fillna(age_avg)
test['Age'] = train['Age'].astype(int)
test['Age'] = test['Age'].astype(int)
train['Age'] = np.where(train['Age'] <= 16, 0, train['Age'])
train['Age'] = np.where((train['Age'] > 16) & (train['Age'] <= 32), 1, train['Age'])
train['Age'] = np.where((train['Age'] > 32) & (train['Age'] <= 48), 2, train['Age'])
train['Age'] = np.where((train['Age'] > 48) & (train['Age'] <= 64), 3, train['Age'])
train['Age'] = np.where(train['Age'] > 64, 4, train['Age'])
test['Age'] = np.where(test['Age'] <= 16, 0, test['Age'])
test['Age'] = np.where((test['Age'] > 16) & (test['Age'] <= 32), 1, test['Age'])
test['Age'] = np.where((test['Age'] > 32) & (test['Age'] <= 48), 2, test['Age'])
test['Age'] = np.where((test['Age'] > 48) & (test['Age'] <= 64), 3, test['Age'])
test['Age'] = np.where(test['Age'] > 64, 4, test['Age'])
train['Age'] = train['Age'].astype(int)
test['Age'] = test['Age'].astype(int)

# 없앨 feature들,,
train = train.drop(['Cabin'], axis=1)
test = test.drop(['Cabin'], axis=1)
train = train.drop(['Name'], axis=1)
test = test.drop(['Name'], axis=1)
train = train.drop(['Ticket'], axis=1)
test = test.drop(['Ticket'], axis=1)

In [21]:
train

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Name_length
0,1,0,3,0,1,1,0,0,1,23
1,2,1,1,1,2,1,0,3,2,51
2,3,1,3,1,1,0,0,1,1,22
3,4,1,1,1,2,1,0,3,1,44
4,5,0,3,0,2,0,0,1,1,24
5,6,0,3,0,1,0,0,1,3,16
6,7,0,1,0,3,0,0,3,1,23
7,8,0,3,0,0,3,1,2,1,30
8,9,1,3,1,1,0,2,1,1,49
9,10,1,2,1,0,1,0,2,2,35
10,11,1,3,1,0,1,1,2,1,31
11,12,1,1,1,3,0,0,2,1,24
12,13,0,3,0,1,0,0,1,1,30
13,14,0,3,0,2,1,5,3,1,27
14,15,0,3,1,0,0,0,0,1,36
15,16,1,2,1,3,0,0,2,1,32
16,17,0,3,0,0,4,1,2,3,20
17,18,1,2,0,1,0,0,1,1,28
18,19,0,3,1,1,1,0,2,1,55
19,20,1,3,1,1,0,0,0,2,23
20,21,0,2,0,2,0,0,2,1,20
21,22,1,2,0,2,0,0,1,1,21
22,23,1,3,1,0,0,0,1,3,27
23,24,1,1,0,1,0,0,3,1,28
24,25,0,3,1,0,3,1,2,1,29
25,26,1,3,1,2,1,5,3,1,57
26,27,0,3,0,1,0,0,0,2,23
27,28,0,1,0,1,3,2,3,1,30
28,29,1,3,1,1,0,0,0,3,29
29,30,0,3,0,1,0,0,0,1,19
...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,0,1,1,0,1,1,27
862,863,1,1,1,2,0,0,2,1,51
863,864,0,3,1,1,8,2,3,1,33
864,865,0,2,0,1,0,0,1,1,22
865,866,1,2,1,2,0,0,1,1,24
866,867,1,2,1,1,1,0,1,2,28
867,868,0,1,0,1,0,0,3,1,36
868,869,0,3,0,1,0,0,1,1,27
869,870,1,3,0,0,1,1,1,1,31
870,871,0,3,0,1,0,0,0,1,17
871,872,1,1,1,2,1,1,3,1,48
872,873,0,1,0,2,0,0,0,1,24
873,874,0,3,0,2,0,0,1,1,27
874,875,1,2,1,1,1,0,2,2,37
875,876,1,3,1,0,0,0,0,2,32
876,877,0,3,0,1,0,0,1,1,29
877,878,0,3,0,1,0,0,0,1,20
878,879,0,3,0,1,0,0,0,1,18
879,880,1,1,1,3,0,1,3,2,45
880,881,1,2,1,1,0,1,2,1,44
881,882,0,3,0,2,0,0,0,1,18
882,883,0,3,1,1,0,0,1,1,28
883,884,0,2,0,1,0,0,1,1,29
884,885,0,3,0,1,0,0,0,1,22
885,886,0,3,1,2,0,5,2,3,36
886,887,0,2,0,1,0,0,1,1,21
887,888,1,1,1,1,0,0,2,1,28
888,889,0,3,1,1,1,2,2,1,40
889,890,1,1,0,1,0,0,2,2,21
890,891,0,3,0,1,0,0,0,3,19

In [22]:
# w, x값 받아서 방정식값 출력
def lin_val(x_arr):
    temparr = []
    for x in x_arr:
        temparr.append([x])
    linalg = np.asmatrix([w_arr]) * np.asmatrix(temparr)
    result = linalg.A
    return result[0][0]

# 일단 w0, w1, w2, w3만 사용, 더쓸거면 추가!!
## sex, age, fare

In [23]:
w_arr = []    # w값들을 배열에 저장해서 사용할 겁니다.
# 일단은 w 두개!
w_arr=[random.random(), random.random(), random.random(), random.random()]

x_arr = []
for i in range(train.shape[0]):
    x_arr.append([0, train['Sex'][i], train['Age'][i], train['Embarked'][i]])

In [24]:
w_arr

[0.7357618808747446, 0.7094823668607358, 0.951490999184767, 0.6426083068318627]

In [25]:
# sigmoid func
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
# predicting func
def pred_probability(x_arr):
    z = lin_val(x_arr)
    return sigmoid(z)
# loss func
def cost_func():
    sum = 0
    for i in range(train.shape[0]):
        probability = pred_probability(x_arr[i])
        sum += y[i] * np.log(probability) + (1 - y[i]) * np.log(1 - probability)
    total_cost = -(1/train.shape[0]) * sum
    return total_cost

# x값 추가되면 바꿔줘야함...

In [26]:
predicted_right = 0
for index, row in train.iterrows():
    probability = pred_probability([0, row['Sex'], row['Age'], row['Embarked']])
    if (probability > 0.5):
        if (y[index] == 1):
            predicted_right += 1
    else:
        if (y[index] == 0):
            predicted_right += 1
print("train_accuracy:", (predicted_right/train.shape[0])*100, "%")

train_accuracy: 38.38383838383838 %

In [28]:
# cost 함수 미분한것, w_num번째 w값에 대해 미분?
def gradient_derivate(w_num):
    sum = 0
    for i in range(train.shape[0]):
        probability = pred_probability(x_arr[i])
        if (w_num == 0):
            sum += (probability - y[i])
        else:
            sum += (probability - y[i]) * x_arr[i][w_num]
    return (1/train.shape[0]) * sum

w_zero_graph = []
w_one_graph = []
w_two_graph = []
w_three_graph = []
w_cost = []

import time
# iteration만큼 반복
def converge(iteration):
    alpha = 0.001
    start_time = time.time()
    for i in range(iteration):
        temp_arr = w_arr[:]
        for j in range(len(w_arr)):
            w_arr[j] = w_arr[j] - alpha * gradient_derivate(j)
#             print(j, "번째 w?", w_arr[j], "||", "원래:", temp_arr[j])
            if (j == 0):
                w_zero_graph.append(w_arr[j])
            elif (j == 1):
                w_one_graph.append(w_arr[j])
            elif (j == 2):
                w_two_graph.append(w_arr[j])
            elif (j == 3):
                w_three_graph.append(w_arr[j])
            if (w_arr[j] > 1 or w_arr[j] < -1):
                break
            
        if (i % 100 == 0):
            print(i, "번째 학습,,,")
            w_cost.append(cost_func())
            if (w_cost[-1] < 0.1):
                break
#         print("cost:", w_cost[i])
#         print("-----------------------------------------------------------")
    print("WorkingTime: %s sec" %(time.time() - start_time))
    plt.plot(w_zero_graph, label='w0')
    plt.plot(w_one_graph, label='w1')
    plt.plot(w_two_graph, label='w2')
    plt.plot(w_three_graph, label='w3')
    plt.legend()
    plt.show()
    plt.plot(w_cost, label="cost")
    plt.legend()
    plt.show()

In [ ]:
converge(1001)
predicted_right = 0
for index, row in train.iterrows():
    probability = pred_probability([0, row['Sex'], row['Age'], row['Embarked']])
    if (probability > 0.5):
        if (y[index] == 1):
            predicted_right += 1
    else:
        if (y[index] == 0):
            predicted_right += 1
print("train_accuracy:", (predicted_right/train.shape[0])*100, "%")

0 번째 학습,,,
100 번째 학습,,,
200 번째 학습,,,
300 번째 학습,,,
400 번째 학습,,,

In [30]:
test_index = 892
submission = pd.DataFrame({"PassengerId": [], "Survived": [] })
for index, row in test.iterrows():
    probability = pred_probability([0, row['Sex']])
    if (probability > 0.5):
        submission.loc[test_index] = [test_index, 1]
    else:
        submission.loc[test_] = [test_index, 0]
    test_index += 1
submission['PassengerId'] = submission['PassengerId'].astype(int)
submission['Survived'] = submission['Survived'].astype(int)

892 0
893 1
894 0
895 0
896 1
897 0
898 1
899 0
900 1
901 0
902 0
903 0
904 1
905 0
906 1
907 1
908 0
909 0
910 1
911 1
912 0
913 0
914 1
915 0
916 1
917 0
918 1
919 0
920 0
921 0
922 0
923 0
924 1
925 1
926 0
927 0
928 1
929 1
930 0
931 0
932 0
933 0
934 0
935 1
936 1
937 0
938 0
939 0
940 1
941 1
942 0
943 0
944 1
945 1
946 0
947 0
948 0
949 0
950 0
951 1
952 0
953 0
954 0
955 1
956 0
957 1
958 1
959 0
960 0
961 1
962 1
963 0
964 1
965 0
966 1
967 0
968 0
969 1
970 0
971 1
972 0
973 0
974 0
975 0
976 0
977 0
978 1
979 1
980 1
981 0
982 1
983 0
984 1
985 0
986 0
987 0
988 1
989 0
990 1
991 0
992 1
993 0
994 0
995 0
996 1
997 0
998 0
999 0
1000 0
1001 0
1002 0
1003 1
1004 1
1005 1
1006 1
1007 0
1008 0
1009 1
1010 0
1011 1
1012 1
1013 0
1014 1
1015 0
1016 0
1017 1
1018 0
1019 1
1020 0
1021 0
1022 0
1023 0
1024 1
1025 0
1026 0
1027 0
1028 0
1029 0
1030 1
1031 0
1032 1
1033 1
1034 0
1035 0
1036 0
1037 0
1038 0
1039 0
1040 0
1041 0
1042 1
1043 0
1044 0
1045 1
1046 0
1047 0
1048 1
1049 1
1050 0
1051 1
1052 1
1053 0
1054 1
1055 0
1056 0
1057 1
1058 0
1059 0
1060 1
1061 1
1062 0
1063 0
1064 0
1065 0
1066 0
1067 1
1068 1
1069 0
1070 1
1071 1
1072 0
1073 0
1074 1
1075 0
1076 1
1077 0
1078 1
1079 0
1080 1
1081 0
1082 0
1083 0
1084 0
1085 0
1086 0
1087 0
1088 0
1089 1
1090 0
1091 1
1092 1
1093 0
1094 0
1095 1
1096 0
1097 0
1098 1
1099 0
1100 1
1101 0
1102 0
1103 0
1104 0
1105 1
1106 1
1107 0
1108 1
1109 0
1110 1
1111 0
1112 1
1113 0
1114 1
1115 0
1116 1
1117 1
1118 0
1119 1
1120 0
1121 0
1122 0
1123 1
1124 0
1125 0
1126 0
1127 0
1128 0
1129 0
1130 1
1131 1
1132 1
1133 1
1134 0
1135 0
1136 0
1137 0
1138 1
1139 0
1140 1
1141 1
1142 1
1143 0
1144 0
1145 0
1146 0
1147 0
1148 0
1149 0
1150 1
1151 0
1152 0
1153 0
1154 1
1155 1
1156 0
1157 0
1158 0
1159 0
1160 1
1161 0
1162 0
1163 0
1164 1
1165 1
1166 0
1167 1
1168 0
1169 0
1170 0
1171 0
1172 1
1173 0
1174 1
1175 1
1176 1
1177 0
1178 0
1179 0
1180 0
1181 0
1182 0
1183 1
1184 0
1185 0
1186 0
1187 0
1188 1
1189 0
1190 0
1191 0
1192 0
1193 0
1194 0
1195 0
1196 1
1197 1
1198 0
1199 0
1200 0
1201 1
1202 0
1203 0
1204 0
1205 1
1206 1
1207 1
1208 0
1209 0
1210 0
1211 0
1212 0
1213 0
1214 0
1215 0
1216 1
1217 0
1218 1
1219 0
1220 0
1221 0
1222 1
1223 0
1224 0
1225 1
1226 0
1227 0
1228 0
1229 0
1230 0
1231 0
1232 0
1233 0
1234 0
1235 1
1236 0
1237 1
1238 0
1239 1
1240 0
1241 1
1242 1
1243 0
1244 0
1245 0
1246 1
1247 0
1248 1
1249 0
1250 0
1251 1
1252 0
1253 1
1254 1
1255 0
1256 1
1257 1
1258 0
1259 1
1260 1
1261 0
1262 0
1263 1
1264 0
1265 0
1266 1
1267 1
1268 1
1269 0
1270 0
1271 0
1272 0
1273 0
1274 1
1275 1
1276 0
1277 1
1278 0
1279 0
1280 0
1281 0
1282 0
1283 1
1284 0
1285 0
1286 0
1287 1
1288 0
1289 1
1290 0
1291 0
1292 1
1293 0
1294 1
1295 0
1296 0
1297 0
1298 0
1299 0
1300 1
1301 1
1302 1
1303 1
1304 1
1305 0
1306 1
1307 0
1308 0
1309 0

In [33]:
submission.to_csv("my_first_submission.csv", index=False)